#!/bin/bash
echo "Pushing source..."
git push

if [ ! -d public/.git ]; then
  rm -rf public
  REMOTE="$(git remote get-url origin)"
  git clone "${REMOTE}" public
fi

docker run --rm -v "${PWD}:/src" -p 1313:1313 hugo-alpine hugo

cd public
git add -A
git commit -m "$(date)"
echo "Pushing build..."
git push
