#!/bin/bash
set -euo pipefail

if ! [ -f hugo-alpine.tar.gz ]; then
  ./build_docker
fi

docker run --platform linux/amd64 --rm -v "${PWD}:/src" \
  -p 1313:1313 hugo-alpine-amd64 hugo --watch serve --buildDrafts --bind 0.0.0.0
