#!/bin/bash
set -euo pipefail

# https://stackoverflow.com/a/67149569/304706
function kebab_case() {
  echo -n "$1" |\
  sed 's/--/-/g' |\
  sed 's/\([\/]\)-/\1/g' |\
  tr '[:upper:]' '[:lower:]' |\
  sed 's/[^[:alnum:]+.-]/-/g' |\
  tr --squeeze-repeats -
}

# Param: $1 - title
# Runs: ./hugo new posts/yyyy-mm-dd-<title kebab case>.md
function new_post() {
  local title="$1"
  local date="$(date +%Y-%m-%d)"
  local slug="$(kebab_case "$title")"
  local path="$date-$slug.md"
  local full_path="$(pwd)/content/posts/$path"

  if [ -f "$full_path" ]; then
    echo "File already exists: $full_path"
    return 1
  fi

  # Create folder for images: ./static/images/yyyy/mm
  local year="${date:0:4}"
  local month="${date:5:2}"
  local images_path="static/images/$year/$month"
  local assets_path="static/post-assets/$year/$month"
  echo "Creating post asset directories: $images_path, $assets_path"
  mkdir -p "$images_path"
  mkdir -p "$assets_path"

  echo "Creating new post: $full_path"
  ./hugo new -f yaml posts/$path

  sed "s/title: \"\"/title: \"$title\"/" $full_path | grep -v 'description: ""' > $full_path.tmp
  mv $full_path.tmp $full_path

  # Open the post in the editor
  open "$full_path"

  # Open the post in the browser (e.g. http://localhost:1313/posts/yyyy-mm-dd-<title kebab case>)
  open "http://localhost:1313/posts/${path//.md/}"
}

new_post "$@"
