routes:

collections:
  /posts/:
    filter: "tag:hash-new-routing"
    permalink: /posts/{year}-{month}-{day}-{slug}/
    template: index

  /logs/:
    filter: "tag:logs"
    permalink: /logs/{slug}/
    template: index

  /:
    permalink: /{year}/{month}/{day}/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
